<!--# Foreword

## Alessandra Zampieri, Director, Institute ...

## Steve Cadrin, Professor, University of Massachusets-->

# Introduction

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(dev='png', dev.args=list(type="cairo"), warning=FALSE)
library(lattice)
lattice.options(default.args = list(as.table = TRUE))
```

## Book concept and target audience

## The "Assessment for All" Initiative (a4a)

The European Commission Joint Research Centre's (JRC) "Assessment for All" Initiative (a4a) was launched to simplify and standardize the complex methodologies often employed in fisheries science. The a4a philosophy focuses on creating flexible, modular frameworks that can accommodate various levels of data availability, different regional needs, and stakeholder objectives. The main aim was to develop, test, and distribute methods able to be used to assess a large number of stocks in an operational time frame, and to build the necessary expertise on stock assessment and advice provision.

According to @EJ_etal_2014, the long-term strategy of a4a is to increase the number of stock assessments by reducing the workload required to run each analysis and by bringing more scientists into fisheries management advice. The first is achieved by developing a working framework with the methods required to run all the analyses a stock assessment needs. Such approach should make the model exploration and selection processes easier, as well as decreasing the burden of moving between software platforms. The second can be achieved by making the analysis more intuitive, thereby attracting more experts to join stock assessment teams.

One major step to achieve the a4a goals was the development of a stock assessment model that could be applied rapidly to a large number of stocks and for a wide range of applications: traditional stock assessment, conditioning of operating models, forecasting, or informing harvest control rules in MSE algorithms.

The modular nature of a4a allows for the integration of data from diverse sources, including biological, environmental, and socioeconomic datasets, ensuring comprehensive assessments. This inclusivity enhances the ability to predict stock dynamics and evaluate the impacts of fishing and environmental changes.

While a4a simplifies traditional assessment approaches, it faces challenges such as ensuring the quality and consistency of input data, especially in regions with limited monitoring infrastructure. To address this, the initiative incorporates uncertainty into its models, leveraging MCMC frameworks and other statistical tools to account for variability in data quality and ecosystem processes.

The a4a framework has been applied in various European fisheries to improve stock assessment practices. In the Mediterranean Sea it has been used for more than 200 stock assessments, as of 2024 in [(GFCM)](https://www.fao.org/gfcm/data/star/en/) and [(STECF)](https://stecf.ec.europa.eu/data-dissemination/medbs_en).

Some of the key elements of stock assessment are the quantity, quality and aggregation level of the data available. As in many other models the data will condition the type of models that can be used. In a4a the minimum set of data, loosely defined as a "moderate data" level, consists of:

- volume of catches in weight (which should both include landings and discards);
- length structure of the catches (based on selectivity studies or direct observations);
- natural mortality by length;
- proportion of mature individuals by length;
- age-length key or growth model;
- length-weight relationship;
- index or indices of abundance and its length structure, or indices of biomass, which could originate from either a scientific survey or a commercial CPUE series;

## Multi-stage modelling approach

In ecological and population dynamics modeling, one can choose between integrated models, which estimate correlated parameters together, and multi-stage models, which separate estimation into distinct steps. These approaches differ in complexity, data requirements, interpretability, and their ability to address various uncertainties. The selection depends largely on the study objectives, the available data, and the system's ecological complexity.

Integrated models estimate all parameters within a unified framework, accounting for correlations and interactions between variables such as growth, natural mortality, recruitment, and environmental factors. This approach can provide a realistic depiction of biological systems by preserving dependencies and feedback loops, which are crucial for understanding processes like density dependence or predator-prey interactions [@MCAPAM2023]. Integrated models are particularly advantageous for ecosystem-based management, where interactions among multiple factors need to be captured. However, the complexity of these models makes them computationally intensive and sensitive to data quality.

On the other hand, multi-stage approaches estimate parameters such as growth or natural mortality independently before incorporating them into broader models. This step-wise approach simplifies estimation, reducing computational demands and mitigating issues like parameter confounding. For example, fisheries often use empirical relationships to estimate natural mortality ($M$) based on growth parameters or life history traits before including M in stock assessment models [@Maceina_etal_2016]. However, this decoupling may overlook dynamic interactions, such as how growth influences mortality, potentially leading to biased or incomplete inferences about ecosystem dynamics [@Jacobsen_etal_2018].

Dealing with uncertainty is a critical aspect of both approaches. Integrated models explicitly quantify and propagate uncertainties across correlated parameters. These models incorporate multiple sources of variability, including observation, process, and structural uncertainties, enhancing the robustness of predictions [@López_etal_2017]. Conversely, multi-stage models often treat parameter estimates as fixed values, which can underestimate uncertainty propagation in subsequent analyses. However, by treating initial stage estimates as distributions rather than point estimates, multi-stage models can partially address this limitation.

For fisheries science, the choice between these models often depends on management goals and data availability. Integrated models are better suited for forecasting fish abundance or evaluating complex ecological interactions, such as predator-prey dynamics or responses to environmental variability [@Robertson_etal_2022]. Meanwhile, multi-stage models are advantageous for practical applications, such as fisheries stock assessment and scientific advice, where simplicity and robustness take precedence over ecological nuance. For example, empirical estimates of $M$, derived from life-history traits, provide reliable inputs for subsequent models, avoiding the parameter confounding that often occurs in integrated frameworks.

Despite the intuitive advantages of integrated models, they are not a panacea for poor quality data or model structure uncertainty in stock assessment. There are also several disadvantages, mostly related to the potential for model misspecification, the complexity of the resulting model, and the associated, often considerable, computational requirements (e.g. the use of remotely sensed environmental information). Consequently, in some situations, the traditional two-stage model remains a better approach [@maunderPunt2013].

## Stock Assessment Process

The following table breaks down the stock assessment process into three stages: (i) input data preparation, (ii) stock assessment model fitting, and (iii) provision of scientific advice. This breakdown is designed to explain the a4a approach, offering a general framework that outlines the sequence of analyses in the stock assessment process. Each stage includes a plethora of analyses and procedures tailored to an specific stock, considering the available data, time, and resources.

| Stage | Description |
|:----|:----|
| **Input data preparation** | Preparation of catch data, potentially computing both landings and discards. Preparation of biological data, including maturity, length-weight relationships, natural mortality, and individual growth. Conversion of length data into age data. |
| **Stock assessment model fit** | Fitting the model to data, inspecting diagnostics such as residuals, retrospective analyses, and hindcasts. Fitting the stock-recruitment model to recruitment and spawning stock biomass (SSB) estimates from the stock assessment model fit or within the model itself. |
| **Scientific advice provision** | Estimation of reference points. Assessment of stock status based on reference points and model estimates of SSB and fishing mortality. Running projections under different scenarios. Providing reports with policy outcome evaluations. |
Table: (\#tab:sastages) Stock assessment process stages

The main purpose of the above table is to clarify a4a's multi-stage approach to stock assessment. For instance, parameters like natural mortality and individual growth are estimated outside the stock assessment model fitting process, unlike how it is often done in integrated analyses. The stock-recruitment relationship, however, can be estimated within the model, as is common in integrated analyses. This mixed approach seeks to exclude highly correlated processes from the model while incorporating those that can enhance the robustness of the stock assessment model fit.

On the other hand, since natural mortality and individual growth are very important processes acting at a very low level in terms of data processing, there are specific methods to deal with conditioning those processes, in those cases when there is no data or very limited data is available, and to provide the opportunity to propagate their uncertainty into stock assessment.

<!--## Stock assessment as a linear model-->

<!--Stock assessment models often involve complex relationships between biological, environmental, and fishery-dependent variables. By framing these relationships within a linear modeling structure, researchers can leverage a broad range of robust statistical techniques. In particular, the submodel formulation using linear models enables the direct application of powerful tools in R, such as `mgcv` [@R-mgcv] for generalized additive models (GAMs) or traditional factorial designs using `lm()`. These tools not only enhance modeling flexibility but also allow scientists to easily test hypotheses, explore interactions, and fit smooth trends to noisy data, all crucial aspects when assessing dynamic biological systems like fish populations.

The conceptual 'language' of linear models has evolved significantly within the statistical community, offering a structured and elegant way to specify complex relationships without delving into cumbersome mathematical notation. This symbolic approach simplifies model specification, fosters reproducibility, and promotes accessibility, particularly among interdisciplinary teams where not all members may have advanced statistical training. Researchers can define model structures using intuitive formula syntax, where variables and their interactions are easily represented. Thus, linear modeling acts as a bridge between statistical theory and practical application, fostering a deeper shared understanding among scientists and stakeholders.

Historically, several key contributions have shaped the symbolic expression of linear models. @Nelder_1965 first introduced concise notation for randomized block designs, streamlining the analysis of experimental layouts common in agricultural and ecological studies. Building upon this, @Wilkinson_etal_1973 developed a comprehensive symbolic system for representing factorial designs, which allowed statisticians to describe main effects and interactions succinctly. Later, @hastie1990generalized extended this framework by incorporating smoothers, flexible functions that model nonlinear relationships, using familiar linear model notation. This lineage of innovation was further consolidated and expanded through the work of @chambers1991statistical, particularly in the S programming environment, laying the groundwork for many statistical packages used today.

In the context of fisheries science, adopting this linear modeling philosophy offers numerous advantages. It democratizes model development by making it easier for researchers with varying statistical backgrounds to construct, modify, and interpret models. Moreover, it aligns stock assessment practices with contemporary developments in statistical computing, facilitating integration with advanced methods like machine learning and Bayesian modeling. As the complexity of ecological systems becomes increasingly recognized, the flexibility and communicability of linear model-based frameworks will remain indispensable tools for advancing stock assessment methodologies and ensuring sustainable management of marine resources.-->

## Data used in the book

### Plaice in area FAO 27, ICES area IV

North sea plaice is an important demersal flatfish that has been targeted by different fleets operating in the area, but most importantly by beam and otter trawlers. This fishery has always had a large discard rate, which currently accounts for more than 60% of the catch. The stock has grown in recent years with the decrease of fishing mortality. A number of scientific surveys sample plaice, both in coastal areas, where spawning takes place, and in deeper waters.

### European hake in FAO 37, GSAs 1,5,6,7

European hake is an important demersal species targeted by Mediterranean fishing fleets in several regions, mainly by bottom trawling, with In GSA 5 (Balearic Islands), bottom trawlers use different fishing tactics depending on the depth, with hake being targeted mainly on the deep shelf and the upper slope. In GSA 6, the fishery is also dominated by trawlers, with a large fleet operating on the shelf and slope and showing relatively stable catches. In GSA 7 (Gulf of Lions), hake is targeted by both French and Spanish vessels using a variety of gear types, including trawlers, gillnets and longlines.

### Red mullet in FAO 37, GSA 9

Red mullets is a key commercial species in GSA 9.They can be found in sandy and muddy areas, and most are caught by bottom trawlers. Small scale fisheries also catch some using nets. The amount of discards reported is very low and considered to be negligible. Trawl fisheries developed along the continental shelf and upper slope. Smaller vessels operate almost exclusively on the continental shelf. Red mullet is intensively exploited during its recruitment from September to November

### Redfish simulated length data

This is a length-based dataset simulated with GADGET [@gadget].

## Notation

Along this book the notation presented in Table \@ref(tab:mathsnotation) will be used. Mathematical descriptions will be kept as simple as possible for readability.

|Type|Symbol|Description|
|:---|-----:|:----------|
|variables| | |
| |$C$ | catches|
| |$F$ | fishing mortality |
| |$M$ | natural mortality |
| |$R$ | recruitment |
| |$Q$ | vessel or fleet catchability |
| |$w$ | weights |
| |$l$ | likelihood |
| |$I$ | abundance index |
| |$S$ | spawning stock biomass |
| |$CV$ | coefficient of variation |
| |$D$ | residuals or deviances |
| |$N$ | population numbers |
| |$\beta, \gamma$ | parameters |
| |$a$ | stock-recruitment parameter |
| |$b$ | stock-recruitment parameter |
| |$\sigma^2$ | variance of catch |
| |$\tau^2$ | variance of index |
| |$\phi^2$ | variance of predicted recruitment |
| |$\upsilon^2$ | variance of residuals |
|subscripts | | |
| |$a$ | age |
| |$y$ | year |
| |$C$ | catch |
| |$I$ | abundance index |
| |$N$ | normal distribution |
| |$s$ | survey |
| |$SR$ | stock recruitment relationship |
|superscripts and accents | | |
| |$\hat{}$ | observation |
| |$\tilde{}$ | prediction |
| |$c$ | catches |
| |$s$ | abundance index |

Table: (\#tab:mathsnotation) Mathematical notation
