# Smoothness, mgcv and fits

```{r}
data(hke1567)
data(hke1567.idx)
```

Set list of fmodels to test

```{r}
fmodsk <- list()
for(i in 3:12) {
  fmodsk[[paste0(i)]] <- as.formula(paste0("~s(age, k =3)+s(year, k=",i,")"))
}
```

Run several stock assessments

```{r}
fitsk <- FLa4a:::multisca(FLStocks(stk), list(idx), fmodel = fmodsk)
```

```{r}
plotFitStats <- function(fits){
  gcv = lapply(fits,function(x) fitSumm(x)['gcv',])
  bic = lapply(fits, function(x) BIC(x))
  
  df <- data.frame(unlist(gcv), unlist(bic))
  
  df$fit <- as.numeric(gsub("fit", "",names(gcv)))
  names(df) <- c("GCV","BIC","fit")
  df <- df[complete.cases(df),]
  
  plot(df$fit, df$GCV, type = "b", col = "blue", 
       ylim = c(0.75*min(df$GCV), 1.25*max(df$GCV)), ylab = "", xlab = "fit")
  par(new = TRUE)
  plot(df$fit, df$BIC, type = "b", col = "red", 
       ylim = c(0.75*min(df$BIC), 1.25*max(df$BIC)), axes = FALSE, xlab = "", ylab = "")
  axis(4)                
  abline(v=df[min(df$GCV)==df$GCV,]$fit, col = "blue",lty = 2)
  abline(v=df[min(df$BIC)==df$BIC,]$fit, col = "red",lty = 2)
  legend("topleft", legend = c("GCV", "BIC"), col = c("blue", "red"), lty = 1)
}
```

```{r}
plotFitStats(fitsk)
```


