# Modelling fleet selectivity

## Modelling fleets with different proportions of the catch covariate

```{r, eval = FALSE}
cp1 <- cp2 <- catch.n(ple4)
pa <- c(0.2, 0.3, 0.5, 0.5, 0.6, 0.7, 0.6, 0.6, 0.6, 0.6)
na <- nrow(cp1)
for(i in 1:na) cp1[i][] <- mean(rbinom(100, 1, pa[i]))
for(i in 1:na) cp2[i][] <- mean(rbinom(100, 1, 1-pa[i]))
cp2 <- 1-cp1

fmod <- ~ s(year, k = 20, by = cp1) + s(year, k = 20, by = cp2) + s(age, k = 5)
fit <- sca(ple4, ple4.indices, fmodel=fmod, covar=FLQuants(cp1=cp1, cp2=cp2))

fmod <- ~s(year, k=20) + s(age, k=5)
fit0 <- sca(ple4, ple4.indices, fmodel=fmod)

plot(FLStocks(f1=ple4+fit, f0=ple4+fit0))
```

```{r, eval = FALSE}
fit
b <- coef(simulate(stkmodel(fit), nsim = 100))
by1 <- grep("fMod:s[(]age[)]:by1", dimnames(b)$params)
by2 <- grep("fMod:s[(]age[)]:by2", dimnames(b)$params)

# doesnt work
getX(~ s(age, k = 3), data.frame(age = dims(ple4)$min:dims(ple4)$max))

# need covars to make it work
df <- data.frame(
  year = rep(dims(ple4)$minyear:dims(ple4)$maxyear, each = dims(ple4)$age),
  age = dims(ple4)$min:dims(ple4)$max,
  cp1 = c(cp1[, 1]),
  cp2 = c(cp2[, 1])
)

X <- getX(fmodel(fit), df)
# just keep first 10 rows (ages 1:10)
X <- X[1:10,]

sims1 <- exp(X[,by1] %*% b[by1,])
sims2 <- exp(X[,by2] %*% b[by2,])

par(mfrow = c(2, 1))
matplot(sims1, type = "l")
matplot(sims2, type = "l")

```


```{r, eval = FALSE}

fmodel0 <- ~ s(age, k = 5) + s(year, k = 10)
fit0 <- sca(ple4, ple4.indices, fmodel = fmodel0)


plot(splines::bs(year) %*% c(0, 1, 1))

plot(pnorm(year, 1990, 5), type = "b")


fmodel2 <- ~
  s(age, k = 3, by = cbind(pnorm(year, 1990, 5), 1 - pnorm(year, 1990, 5))) +
  s(year, k = 18)
fit2 <- sca(ple4, ple4.indices, fmodel = fmodel2)

xyplot(data ~ age | year > 1990, groups = year, data = harvest(fit2), type = "l")

wireframe(harvest(fit2))



b <- coef(simulate(stkmodel(fit2), nsim = 1000))
by1 <- grep("fMod:s[(]age[).]", dimnames(b)$params)
by2 <- grep("fMod:s[(]age[)]:", dimnames(b)$params)

X <- getX(fmodel(fit2), as.data.frame(catch.n(ple4)))

sims1 <- X[1:10, by1] %*% b[by1, ]
sims2 <- X[nrow(X) - (10:1) + 1, by2] %*% b[by2, ]

# get quantiles
simsqs1 <- t(apply(sims1, 1, quantile, c(0.25, .5)))

par(mfrow = c(2, 1))
matplot(sims1, type = "l")
matplot(sims2, type = "l")


```


```{r, eval = FALSE}

dm <- dims(ple4)
# simulate a simple model
age <- dm$min:dm$max
year <- dm$minyear:dm$maxyear
s1 <- c(splines::bs(age) %*% c(.2, 1, 1))
s2 <- c(splines::bs(age) %*% c(-1, 1, 0))

s1 <- s1 / max(s1)
s2 <- s2 / max(s2)

weight <- pnorm(year, 1990, 5)

obj <- catch.n(ple4)

y <- s1 %o% weight + s2 %o% (1 - weight)

yobs <- y + rnorm(length(y), 0, 0.01)

dat <- data.frame(
  year = rep(year, each = length(age)),
  age = rep(age, length(year)),
  y = c(yobs)
)

L <- cbind(rep(weight, each = dm$age), 1 - rep(weight, each = dm$age))

agem <- cbind(dat$age, dat$age)

library(mgcv)
fit0 <- gam(y ~ s(age, k = 5) + s(year, k = 20), data = dat)

fit1 <- gam(y ~ s(agem, k = 5, by = L), data = dat)


obj[] <- fitted(fit1)

wireframe(obj)
xyplot(data ~ age | year > 1990, groups = year, data = obj, type = "l")

```