<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 The statistical catch-at-age stock assessment framework with Markov Chain Monte Carlo (MCMC)  | Fish stock assessment with R - DRAFT</title>
  <meta name="description" content="How to do stock assessment in R using the a4a framework" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="10 The statistical catch-at-age stock assessment framework with Markov Chain Monte Carlo (MCMC)  | Fish stock assessment with R - DRAFT" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="How to do stock assessment in R using the a4a framework" />
  <meta name="github-repo" content="ejardim/a4abook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 The statistical catch-at-age stock assessment framework with Markov Chain Monte Carlo (MCMC)  | Fish stock assessment with R - DRAFT" />
  
  <meta name="twitter:description" content="How to do stock assessment in R using the a4a framework" />
  



<meta name="date" content="2025-06-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="uncertainty.html"/>
<link rel="next" href="reference-points.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Stock assessment framework</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Before starting</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#installing-and-loading-libraries"><i class="fa fa-check"></i><b>1.1</b> Installing and loading libraries</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#how-to-read-this-document"><i class="fa fa-check"></i><b>1.2</b> How to read this document</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#how-to-get-help"><i class="fa fa-check"></i><b>1.3</b> How to get help</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.4</b> Acknowledgements</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i><b>1.5</b> License</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction.html"><a href="introduction.html#book-concept-and-target-audience"><i class="fa fa-check"></i><b>2.1</b> Book concept and target audience</a></li>
<li class="chapter" data-level="2.2" data-path="introduction.html"><a href="introduction.html#the-assessment-for-all-initiative-a4a"><i class="fa fa-check"></i><b>2.2</b> The “Assessment for All” Initiative (a4a)</a></li>
<li class="chapter" data-level="2.3" data-path="introduction.html"><a href="introduction.html#multi-stage-modelling-approach"><i class="fa fa-check"></i><b>2.3</b> Multi-stage modelling approach</a></li>
<li class="chapter" data-level="2.4" data-path="introduction.html"><a href="introduction.html#stock-assessment-process"><i class="fa fa-check"></i><b>2.4</b> Stock Assessment Process</a></li>
<li class="chapter" data-level="2.5" data-path="introduction.html"><a href="introduction.html#data-used-in-the-book"><i class="fa fa-check"></i><b>2.5</b> Data used in the book</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introduction.html"><a href="introduction.html#plaice-in-area-fao-27-ices-area-iv"><i class="fa fa-check"></i><b>2.5.1</b> Plaice in area FAO 27, ICES area IV</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction.html"><a href="introduction.html#european-hake-in-fao-37-gsas-1567"><i class="fa fa-check"></i><b>2.5.2</b> European hake in FAO 37, GSAs 1,5,6,7</a></li>
<li class="chapter" data-level="2.5.3" data-path="introduction.html"><a href="introduction.html#red-mullet-in-fao-37-gsa-9"><i class="fa fa-check"></i><b>2.5.3</b> Red mullet in FAO 37, GSA 9</a></li>
<li class="chapter" data-level="2.5.4" data-path="introduction.html"><a href="introduction.html#redfish-simulated-length-data"><i class="fa fa-check"></i><b>2.5.4</b> Redfish simulated length data</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="introduction.html"><a href="introduction.html#notation"><i class="fa fa-check"></i><b>2.6</b> Notation</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="growth.html"><a href="growth.html"><i class="fa fa-check"></i><b>3</b> Modelling Individual Growth and Using Stochastic Slicing to Convert Length-based Data Into Age-based Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="growth.html"><a href="growth.html#a4agr---the-growth-class"><i class="fa fa-check"></i><b>3.1</b> a4aGr - The growth class</a></li>
<li class="chapter" data-level="3.2" data-path="growth.html"><a href="growth.html#adding-uncertainty-to-growth-parameters-with-a-multivariate-normal-distribution"><i class="fa fa-check"></i><b>3.2</b> Adding uncertainty to growth parameters with a multivariate normal distribution</a></li>
<li class="chapter" data-level="3.3" data-path="growth.html"><a href="growth.html#adding-uncertainty-to-growth-parameters-with-a-multivariate-triangle-distribution"><i class="fa fa-check"></i><b>3.3</b> Adding uncertainty to growth parameters with a multivariate triangle distribution</a></li>
<li class="chapter" data-level="3.4" data-path="growth.html"><a href="growth.html#adding-uncertainty-to-growth-parameters-with-statistical-copulas"><i class="fa fa-check"></i><b>3.4</b> Adding uncertainty to growth parameters with statistical copulas</a></li>
<li class="chapter" data-level="3.5" data-path="growth.html"><a href="growth.html#converting-from-length-to-age-based-data---the-l2a-method"><i class="fa fa-check"></i><b>3.5</b> Converting from length to age based data - the <code>l2a()</code> method</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modelling-natural-mortality.html"><a href="modelling-natural-mortality.html"><i class="fa fa-check"></i><b>4</b> Modelling Natural Mortality</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelling-natural-mortality.html"><a href="modelling-natural-mortality.html#a4am---the-m-class"><i class="fa fa-check"></i><b>4.1</b> <code>a4aM</code> - The M class</a></li>
<li class="chapter" data-level="4.2" data-path="modelling-natural-mortality.html"><a href="modelling-natural-mortality.html#adding-uncertainty-to-natural-mortality-parameters-with-a-multivariate-normal-distribution"><i class="fa fa-check"></i><b>4.2</b> Adding uncertainty to natural mortality parameters with a multivariate normal distribution</a></li>
<li class="chapter" data-level="4.3" data-path="modelling-natural-mortality.html"><a href="modelling-natural-mortality.html#adding-uncertainty-to-natural-mortality-parameters-with-statistical-copulas"><i class="fa fa-check"></i><b>4.3</b> Adding uncertainty to natural mortality parameters with statistical copulas</a></li>
<li class="chapter" data-level="4.4" data-path="modelling-natural-mortality.html"><a href="modelling-natural-mortality.html#computing-natural-mortality-time-series---the-m-method"><i class="fa fa-check"></i><b>4.4</b> Computing natural mortality time series - the <code>m()</code> method</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="stock-assessment-framework.html"><a href="stock-assessment-framework.html"><i class="fa fa-check"></i><b>5</b> Stock assessment framework</a>
<ul>
<li class="chapter" data-level="5.1" data-path="stock-assessment-framework.html"><a href="stock-assessment-framework.html#maths-description"><i class="fa fa-check"></i><b>5.1</b> Maths description </a></li>
<li class="chapter" data-level="5.2" data-path="stock-assessment-framework.html"><a href="stock-assessment-framework.html#model-structure"><i class="fa fa-check"></i><b>5.2</b> Model structure </a></li>
<li class="chapter" data-level="5.3" data-path="stock-assessment-framework.html"><a href="stock-assessment-framework.html#submodel-building-blocks-and-fundamental-r-formulas"><i class="fa fa-check"></i><b>5.3</b> Submodel building blocks and fundamental <code>R</code> formulas</a></li>
<li class="chapter" data-level="5.4" data-path="stock-assessment-framework.html"><a href="stock-assessment-framework.html#the-major-effects-available-for-modelling"><i class="fa fa-check"></i><b>5.4</b> The major effects available for modelling</a></li>
<li class="chapter" data-level="5.5" data-path="stock-assessment-framework.html"><a href="stock-assessment-framework.html#classes-description"><i class="fa fa-check"></i><b>5.5</b> Classes Description </a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-splines.html"><a href="introduction-to-splines.html"><i class="fa fa-check"></i><b>6</b> Introduction to Splines</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introduction-to-splines.html"><a href="introduction-to-splines.html#generalize-to-polynomials"><i class="fa fa-check"></i><b>6.1</b> Generalize to polynomials</a></li>
<li class="chapter" data-level="6.2" data-path="introduction-to-splines.html"><a href="introduction-to-splines.html#thin-plate-spline"><i class="fa fa-check"></i><b>6.2</b> Thin plate spline</a></li>
<li class="chapter" data-level="6.3" data-path="introduction-to-splines.html"><a href="introduction-to-splines.html#the-mgcv-package-inside-a4a"><i class="fa fa-check"></i><b>6.3</b> The <code>mgcv</code> package inside <code>a4a</code></a></li>
<li class="chapter" data-level="6.4" data-path="introduction-to-splines.html"><a href="introduction-to-splines.html#on-the-number-of-knots-k"><i class="fa fa-check"></i><b>6.4</b> On the number of knots <span class="math inline">\(k\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="fitting.html"><a href="fitting.html"><i class="fa fa-check"></i><b>7</b> Fitting</a>
<ul>
<li class="chapter" data-level="7.1" data-path="fitting.html"><a href="fitting.html#fishing-mortality-submodel-f_ay"><i class="fa fa-check"></i><b>7.1</b> Fishing mortality submodel (<span class="math inline">\(F_{ay}\)</span>)</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="fitting.html"><a href="fitting.html#separable-model"><i class="fa fa-check"></i><b>7.1.1</b> Separable model</a></li>
<li class="chapter" data-level="7.1.2" data-path="fitting.html"><a href="fitting.html#model-with-age-year-interaction"><i class="fa fa-check"></i><b>7.1.2</b> Model with age-year interaction</a></li>
<li class="chapter" data-level="7.1.3" data-path="fitting.html"><a href="fitting.html#constant-selectivity-for-contiguous-ages-or-years"><i class="fa fa-check"></i><b>7.1.3</b> Constant selectivity for contiguous ages or years</a></li>
<li class="chapter" data-level="7.1.4" data-path="fitting.html"><a href="fitting.html#time-blocks-selectivity"><i class="fa fa-check"></i><b>7.1.4</b> Time blocks selectivity</a></li>
<li class="chapter" data-level="7.1.5" data-path="fitting.html"><a href="fitting.html#time-changing-selectivity"><i class="fa fa-check"></i><b>7.1.5</b> Time changing selectivity</a></li>
<li class="chapter" data-level="7.1.6" data-path="fitting.html"><a href="fitting.html#closed-form-selection-pattern"><i class="fa fa-check"></i><b>7.1.6</b> Closed form selection pattern</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="fitting.html"><a href="fitting.html#abundance-indices-catchability-submodel-q_ays"><i class="fa fa-check"></i><b>7.2</b> Abundance indices catchability submodel (<span class="math inline">\(Q_{ays}\)</span>)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="fitting.html"><a href="fitting.html#catchability-submodel-for-age-based-indices"><i class="fa fa-check"></i><b>7.2.1</b> Catchability submodel for age based indices</a></li>
<li class="chapter" data-level="7.2.2" data-path="fitting.html"><a href="fitting.html#catchability-submodel-for-age-aggregated-biomass-indices"><i class="fa fa-check"></i><b>7.2.2</b> Catchability submodel for age aggregated biomass indices</a></li>
<li class="chapter" data-level="7.2.3" data-path="fitting.html"><a href="fitting.html#catchability-submodel-for-single-age-indices"><i class="fa fa-check"></i><b>7.2.3</b> Catchability submodel for single age indices</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="fitting.html"><a href="fitting.html#stock-recruitment-submodel-r_y"><i class="fa fa-check"></i><b>7.3</b> Stock-recruitment submodel (<span class="math inline">\(R_y\)</span>)</a></li>
<li class="chapter" data-level="7.4" data-path="fitting.html"><a href="fitting.html#observation-variance-submodel-sigma2_ay-tau2_ays"><i class="fa fa-check"></i><b>7.4</b> Observation variance submodel (<span class="math inline">\(\{\sigma^2_{ay}, \tau^2_{ays}\}\)</span>)</a></li>
<li class="chapter" data-level="7.5" data-path="fitting.html"><a href="fitting.html#initial-year-abundance-submodel-n_ay1"><i class="fa fa-check"></i><b>7.5</b> Initial year abundance submodel (<span class="math inline">\(N_{a,y=1}\)</span>)</a></li>
<li class="chapter" data-level="7.6" data-path="fitting.html"><a href="fitting.html#more-models"><i class="fa fa-check"></i><b>7.6</b> More models</a></li>
<li class="chapter" data-level="7.7" data-path="fitting.html"><a href="fitting.html#data-weigthing"><i class="fa fa-check"></i><b>7.7</b> Data weigthing</a></li>
<li class="chapter" data-level="7.8" data-path="fitting.html"><a href="fitting.html#working-with-covariates"><i class="fa fa-check"></i><b>7.8</b> Working with covariates</a></li>
<li class="chapter" data-level="7.9" data-path="fitting.html"><a href="fitting.html#assessing-admb-files"><i class="fa fa-check"></i><b>7.9</b> Assessing <code>ADMB</code> files</a></li>
<li class="chapter" data-level="7.10" data-path="fitting.html"><a href="fitting.html#missing-observations-in-the-catch-matrix-or-index"><i class="fa fa-check"></i><b>7.10</b> Missing observations in the catch matrix or index</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="diagnostics.html"><a href="diagnostics.html"><i class="fa fa-check"></i><b>8</b> Diagnostics </a>
<ul>
<li class="chapter" data-level="8.1" data-path="diagnostics.html"><a href="diagnostics.html#residuals"><i class="fa fa-check"></i><b>8.1</b> Residuals</a></li>
<li class="chapter" data-level="8.2" data-path="diagnostics.html"><a href="diagnostics.html#predictive-skill"><i class="fa fa-check"></i><b>8.2</b> Predictive skill</a></li>
<li class="chapter" data-level="8.3" data-path="diagnostics.html"><a href="diagnostics.html#aggregated-catch-in-weight"><i class="fa fa-check"></i><b>8.3</b> Aggregated catch in weight</a></li>
<li class="chapter" data-level="8.4" data-path="diagnostics.html"><a href="diagnostics.html#fit-summary-information-and-cross-validation-metrics"><i class="fa fa-check"></i><b>8.4</b> Fit summary, information and cross-validation metrics</a></li>
<li class="chapter" data-level="8.5" data-path="diagnostics.html"><a href="diagnostics.html#retrospective-analysis"><i class="fa fa-check"></i><b>8.5</b> Retrospective analysis</a></li>
<li class="chapter" data-level="8.6" data-path="diagnostics.html"><a href="diagnostics.html#hindcast"><i class="fa fa-check"></i><b>8.6</b> Hindcast</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>9</b> Uncertainty </a>
<ul>
<li class="chapter" data-level="9.1" data-path="uncertainty.html"><a href="uncertainty.html#the-simulate-and-predict-methods"><i class="fa fa-check"></i><b>9.1</b> The <code>simulate</code> and <code>predict</code> methods</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="uncertainty.html"><a href="uncertainty.html#predict"><i class="fa fa-check"></i><b>9.1.1</b> <code>predict()</code></a></li>
<li class="chapter" data-level="9.1.2" data-path="uncertainty.html"><a href="uncertainty.html#simulate"><i class="fa fa-check"></i><b>9.1.2</b> <code>simulate()</code></a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="uncertainty.html"><a href="uncertainty.html#prediction-error"><i class="fa fa-check"></i><b>9.2</b> Prediction error</a></li>
<li class="chapter" data-level="9.3" data-path="uncertainty.html"><a href="uncertainty.html#confidence-interval-coverage"><i class="fa fa-check"></i><b>9.3</b> Confidence interval coverage</a></li>
<li class="chapter" data-level="9.4" data-path="uncertainty.html"><a href="uncertainty.html#propagate-uncertainty-into-stock-assessment"><i class="fa fa-check"></i><b>9.4</b> Propagate uncertainty into stock assessment</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><i class="fa fa-check"></i><b>10</b> The statistical catch-at-age stock assessment framework with Markov Chain Monte Carlo (MCMC) </a>
<ul>
<li class="chapter" data-level="10.1" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#the-mcmc-method-for-sca"><i class="fa fa-check"></i><b>10.1</b> The MCMC method for <code>sca</code></a></li>
<li class="chapter" data-level="10.2" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#diagnostics-with-coda"><i class="fa fa-check"></i><b>10.2</b> Diagnostics with CODA</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#traceplots"><i class="fa fa-check"></i><b>10.2.1</b> Traceplots</a></li>
<li class="chapter" data-level="10.2.2" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#autocorrelation-and-crosscorrelation-analysis"><i class="fa fa-check"></i><b>10.2.2</b> Autocorrelation and crosscorrelation analysis</a></li>
<li class="chapter" data-level="10.2.3" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#geweke-diagnostic"><i class="fa fa-check"></i><b>10.2.3</b> Geweke diagnostic</a></li>
<li class="chapter" data-level="10.2.4" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cumulative-means"><i class="fa fa-check"></i><b>10.2.4</b> Cumulative means</a></li>
<li class="chapter" data-level="10.2.5" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#distribution-density"><i class="fa fa-check"></i><b>10.2.5</b> Distribution density</a></li>
<li class="chapter" data-level="10.2.6" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#gelman-rubin-statistic"><i class="fa fa-check"></i><b>10.2.6</b> Gelman-Rubin statistic</a></li>
<li class="chapter" data-level="10.2.7" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#acceptance-rate"><i class="fa fa-check"></i><b>10.2.7</b> Acceptance rate</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#admbs-arguments-to-tune-the-mcmc-algorithm"><i class="fa fa-check"></i><b>10.3</b> <code>ADMB</code>’s arguments to tune the MCMC algorithm</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#thinning-rate"><i class="fa fa-check"></i><b>10.3.1</b> Thinning rate</a></li>
<li class="chapter" data-level="10.3.2" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#mcscale-and-mcnoscale"><i class="fa fa-check"></i><b>10.3.2</b> mcscale and mcnoscale</a></li>
<li class="chapter" data-level="10.3.3" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#mcprobe"><i class="fa fa-check"></i><b>10.3.3</b> mcprobe</a></li>
<li class="chapter" data-level="10.3.4" data-path="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#mcrb"><i class="fa fa-check"></i><b>10.3.4</b> mcrb</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="reference-points.html"><a href="reference-points.html"><i class="fa fa-check"></i><b>11</b> Reference Points</a>
<ul>
<li class="chapter" data-level="11.1" data-path="reference-points.html"><a href="reference-points.html#yield-per-recruit-reference-points"><i class="fa fa-check"></i><b>11.1</b> Yield per recruit reference points</a></li>
<li class="chapter" data-level="11.2" data-path="reference-points.html"><a href="reference-points.html#stock-recruitment-relationship-based-reference-points"><i class="fa fa-check"></i><b>11.2</b> Stock recruitment relationship based reference points</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="reference-points.html"><a href="reference-points.html#stock-recruitment-after-fitting-the-stock-assessment-model"><i class="fa fa-check"></i><b>11.2.1</b> Stock recruitment after fitting the stock assessment model</a></li>
<li class="chapter" data-level="11.2.2" data-path="reference-points.html"><a href="reference-points.html#stock-recruitment-during-stock-assessment-model-fit"><i class="fa fa-check"></i><b>11.2.2</b> Stock recruitment during stock assessment model fit</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="reference-points.html"><a href="reference-points.html#economics-reference-points"><i class="fa fa-check"></i><b>11.3</b> Economics reference points</a></li>
<li class="chapter" data-level="11.4" data-path="reference-points.html"><a href="reference-points.html#computing-user-specific-reference-points"><i class="fa fa-check"></i><b>11.4</b> Computing user specific reference points</a></li>
<li class="chapter" data-level="11.5" data-path="reference-points.html"><a href="reference-points.html#assessing-the-status-of-the-stock"><i class="fa fa-check"></i><b>11.5</b> Assessing the status of the stock</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="projections-and-harvest-control-rules.html"><a href="projections-and-harvest-control-rules.html"><i class="fa fa-check"></i><b>12</b> Projections and harvest control rules</a>
<ul>
<li class="chapter" data-level="12.1" data-path="projections-and-harvest-control-rules.html"><a href="projections-and-harvest-control-rules.html#simple-workflow"><i class="fa fa-check"></i><b>12.1</b> Simple workflow</a></li>
<li class="chapter" data-level="12.2" data-path="projections-and-harvest-control-rules.html"><a href="projections-and-harvest-control-rules.html#initial-condition-assumptions"><i class="fa fa-check"></i><b>12.2</b> Initial condition assumptions</a></li>
<li class="chapter" data-level="12.3" data-path="projections-and-harvest-control-rules.html"><a href="projections-and-harvest-control-rules.html#scenarios"><i class="fa fa-check"></i><b>12.3</b> Scenarios</a></li>
<li class="chapter" data-level="12.4" data-path="projections-and-harvest-control-rules.html"><a href="projections-and-harvest-control-rules.html#relative-scenarios"><i class="fa fa-check"></i><b>12.4</b> Relative scenarios</a></li>
<li class="chapter" data-level="12.5" data-path="projections-and-harvest-control-rules.html"><a href="projections-and-harvest-control-rules.html#limits"><i class="fa fa-check"></i><b>12.5</b> Limits</a></li>
<li class="chapter" data-level="12.6" data-path="projections-and-harvest-control-rules.html"><a href="projections-and-harvest-control-rules.html#harvest-control-rules-hcr"><i class="fa fa-check"></i><b>12.6</b> Harvest Control Rules (HCR)</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html"><i class="fa fa-check"></i><b>13</b> Annex - stock assessment workflow</a>
<ul>
<li class="chapter" data-level="13.1" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html#the-mean-model"><i class="fa fa-check"></i><b>13.1</b> The “mean” model</a></li>
<li class="chapter" data-level="13.2" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html#the-age-effects"><i class="fa fa-check"></i><b>13.2</b> The age effects</a></li>
<li class="chapter" data-level="13.3" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html#year-effect-on-fishing-mortality"><i class="fa fa-check"></i><b>13.3</b> Year effect on fishing mortality</a></li>
<li class="chapter" data-level="13.4" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html#year-effect-on-catchability"><i class="fa fa-check"></i><b>13.4</b> Year effect on catchability</a></li>
<li class="chapter" data-level="13.5" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html#the-initial-year-population-abundance-model-aka-n1"><i class="fa fa-check"></i><b>13.5</b> The initial year population abundance model, aka N1</a></li>
<li class="chapter" data-level="13.6" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html#the-stock-recruitment-submodel"><i class="fa fa-check"></i><b>13.6</b> The stock recruitment submodel</a></li>
<li class="chapter" data-level="13.7" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html#the-variance-submodel"><i class="fa fa-check"></i><b>13.7</b> The variance submodel</a></li>
<li class="chapter" data-level="13.8" data-path="annex---stock-assessment-workflow.html"><a href="annex---stock-assessment-workflow.html#final-comments"><i class="fa fa-check"></i><b>13.8</b> Final comments</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>14</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fish stock assessment with R - DRAFT</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> The statistical catch-at-age stock assessment framework with Markov Chain Monte Carlo (MCMC) <a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The previous methods were demonstrated using maximum likelihood estimation (MLE). However, <code>ADMB</code> also supports Markov Chain Monte Carlo (MCMC) methods, which provide significant advantages, particularly when working with complex models that involve many parameters. The key difference is that while MLE finds a single best estimate of parameters by maximizing the likelihood function, MCMC offers a broader perspective by generating an entire distribution of possible values. This approach is more informative because it does not just give the most likely estimate but also helps us understand the uncertainty surrounding it. With MCMC, researchers can incorporate prior knowledge and obtain results that are often more realistic and reliable <span class="citation">(<a href="#ref-gelman2013bayesian">A. Gelman et al. 2013</a>)</span>. This is especially useful when dealing with complicated models where traditional likelihood-based methods struggle, as MCMC allows for efficient exploration of possible solutions without requiring an exact mathematical formulation <span class="citation">(<a href="#ref-gilks1995markov">Gilks, Richardson, and Spiegelhalter 1995</a>; <a href="#ref-robert2005monte">Robert and Casella 2005</a>)</span>.</p>
<p>One of the biggest advantages of MCMC is its flexibility when working with models that have irregular behavior, such as those with multiple peaks or abrupt changes in likelihood. Standard MLE methods assume that the likelihood function behaves smoothly, but this is rarely true in real-world applications. In fisheries, ecology, and other applied sciences, models often have parameters that interact in complex ways, creating likelihood surfaces with ridges and multiple solutions. In these cases, MLE optimizers can easily get stuck in a local peak, failing to find the best possible estimate or underestimating the real uncertainty in the system <span class="citation">(<a href="#ref-neal1993probabilistic">Neal 1993</a>)</span>. Since MCMC uses a probabilistic sampling approach instead of strict optimization, it moves freely across the entire space of possible values, making it more robust and adaptable to challenging problems <span class="citation">(<a href="#ref-robert2005monte">Robert and Casella 2005</a>)</span>.</p>
<p>Traditional MLE-based uncertainty estimation relies on the Hessian matrix, which essentially measures how quickly the likelihood function changes as parameters vary. This method assumes that the shape of the likelihood function is quadratic and roughly the same everywhere. However, this assumption is often unrealistic, especially in models with many parameters or strong correlations among them, as is common in fisheries stock assessment models.</p>
<p>In fields like fisheries science, where models often involve multiple correlated parameters, MCMC provides a much more flexible and realistic way to estimate uncertainty. Unlike MLE, which assumes uncertainty follows a simple symmetrical pattern, MCMC can handle more complex distributions, giving a better representation of real-world variability. This is especially important when estimating key fisheries management indicators, such as spawning stock biomass (<span class="math inline">\(SSB\)</span>) or fishing mortality (<span class="math inline">\(F\)</span>), which influence critical policy decisions. Because MCMC does not impose strict mathematical assumptions about the shape of uncertainty, it produces estimates that are more reflective of real-world conditions, ultimately leading to more informed and reliable management strategies.</p>
<p>When running MCMC, <code>ADMB</code> uses automatic differentiation to improve sampling efficiency and speed <span class="citation">(<a href="#ref-Fournier2012">Fournier et al. 2012</a>)</span>. It supports various sampling algorithms, including Metropolis-Hastings and Hamiltonian Monte Carlo, which help navigate high-dimensional parameter spaces and complex likelihood structures more effectively. This makes <code>ADMB</code> particularly useful in applied sciences like fisheries and ecology, where uncertainty estimation is crucial for decision-making. Additionally, <code>ADMB</code> provides built-in diagnostics to assess MCMC convergence and reliability, ensuring that posterior distributions are well-explored and results are robust <span class="citation">(<a href="#ref-gelman2013bayesian">A. Gelman et al. 2013</a>)</span>.</p>
<!--To evaluate the quality of MCMC sampling, `ADMB` offers several key diagnostics. Autocorrelation analysis to detect dependencies between successive samples; effective sample size (ESS) measures the number of independent samples in the chain. The Gelman-Rubin diagnostic (\(\hat{R}\)) helps assess whether multiple chains have converged to the same distribution, with values close to 1 indicating good convergence. Trace plots visually inspect parameter behavior over iterations, revealing trends or poor mixing. Additionally, `ADMB` monitors the acceptance rate to ensure efficient sampling and provides posterior density estimates to check if the distribution has been properly explored. These tools help users refine their MCMC runs, adjusting sampling length or proposal distributions to improve performance and ensure reliable uncertainty estimates.-->
<p>The manual “A Guide for Bayesian Analysis in AD Model Builder” <span class="citation">(<a href="#ref-monnahan2014admbmcmc">Cole C. Monnahan, Muradian, and Kuriyama 2014</a>)</span> describes and explain a larger group of arguments that can be set when running MCMC with <code>ADMB</code>, which the method <code>sca()</code> uses.</p>
<div id="the-mcmc-method-for-sca" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> The MCMC method for <code>sca</code><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#the-mcmc-method-for-sca" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section shows how the <code>sca()</code> method interfaces with <code>ADMB</code> to use MCMC. For this section we’ll use the hake assessment in Mediterranean areas (gsa) 1, 5, 6 and 7.</p>
<p>We start by fitting the MLE model and calling afterwards the necessary MCMC methods. The outcomes of the MCMC fit need to be inspected to make sure the chain converged and the results are robust. A set of diagnostics are available to do this.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-1" tabindex="-1"></a><span class="co"># load libraries and data</span></span>
<span id="cb202-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-2" tabindex="-1"></a><span class="fu">library</span>(FLa4a)</span>
<span id="cb202-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-3" tabindex="-1"></a><span class="fu">library</span>(ggplotFL)</span>
<span id="cb202-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-4" tabindex="-1"></a><span class="fu">data</span>(hke1567)</span>
<span id="cb202-5"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-5" tabindex="-1"></a><span class="fu">data</span>(hke1567.idx)</span>
<span id="cb202-6"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-6" tabindex="-1"></a>nsim <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb202-7"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-7" tabindex="-1"></a><span class="co"># MLE estimate</span></span>
<span id="cb202-8"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-8" tabindex="-1"></a>fmod <span class="ot">&lt;-</span> <span class="er">~</span><span class="fu">s</span>(age, <span class="at">k =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb202-9"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-9" tabindex="-1"></a>    <span class="fu">s</span>(year, <span class="at">k =</span> <span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb202-10"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-10" tabindex="-1"></a>    <span class="fu">s</span>(year, <span class="at">k =</span> <span class="dv">8</span>, <span class="at">by =</span> <span class="fu">as.numeric</span>(age <span class="sc">==</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb202-11"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-11" tabindex="-1"></a>    <span class="fu">s</span>(year, <span class="at">k =</span> <span class="dv">8</span>, <span class="at">by =</span> <span class="fu">as.numeric</span>(age <span class="sc">==</span> <span class="dv">4</span>))</span>
<span id="cb202-12"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-12" tabindex="-1"></a>qmod <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="sc">~</span><span class="fu">I</span>(<span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>age))))</span>
<span id="cb202-13"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-13" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod)</span>
<span id="cb202-14"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb202-14" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">simulate</span>(fit, nsim)</span></code></pre></div>
<p>To run the MCMC method, one needs to configure a set of arguments, which is done by creating an object of class <code>SCAMCMC</code>. Table <a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#tab:mcargs">10.1</a> describes the arguments available to run the MCMC method, extracted from Monnahan <span class="citation">(<a href="#ref-monnahan2019">Cole C. Monnahan et al. 2019</a>)</span>. For more details on the MCMC configuration in <code>ADMB</code> visit the <code>ADMB</code> website.</p>
<table>
<caption><span id="tab:mcargs">Table 10.1: </span> <code>ADMB</code> MCMC arguments</caption>
<thead>
<tr class="header">
<th align="right">Argument</th>
<th align="left">Default value</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right"><code>mcmc</code></td>
<td align="left"><code>10000</code></td>
<td align="left">Run N MCMC iterations</td>
</tr>
<tr class="even">
<td align="right"><code>mcsave</code></td>
<td align="left"><code>100</code></td>
<td align="left">Save every N th MCMC iteration</td>
</tr>
<tr class="odd">
<td align="right"><code>mcscale</code></td>
<td align="left"></td>
<td align="left">Rescale step size for first N iterations</td>
</tr>
<tr class="even">
<td align="right"><code>mcmult</code></td>
<td align="left"></td>
<td align="left">Rescale the covariance matrix</td>
</tr>
<tr class="odd">
<td align="right"><code>mcrb</code></td>
<td align="left"></td>
<td align="left">Reduce high parameter correlations</td>
</tr>
<tr class="even">
<td align="right"><code>mcprobe</code></td>
<td align="left"><code>0.05</code></td>
<td align="left">Use a fat-tailed proposal distribution</td>
</tr>
<tr class="odd">
<td align="right"><code>mcdiag</code></td>
<td align="left"><code>FALSE</code></td>
<td align="left">Use a diagonal covariance matrix</td>
</tr>
<tr class="even">
<td align="right"><code>mcnoscale</code></td>
<td align="left"><code>FALSE</code></td>
<td align="left">Do not scale the algorithm during</td>
</tr>
<tr class="odd">
<td align="right"><code>mcu</code></td>
<td align="left"><code>FALSE</code></td>
<td align="left">Use a uniform distribution as proposal distribution</td>
</tr>
<tr class="even">
<td align="right"><code>hybrid</code></td>
<td align="left"><code>FALSE</code></td>
<td align="left">Use the hybrid method</td>
</tr>
<tr class="odd">
<td align="right"><code>hynstep</code></td>
<td align="left"></td>
<td align="left">Mean number of steps for the leapfrog method</td>
</tr>
<tr class="even">
<td align="right"><code>hyeps</code></td>
<td align="left"></td>
<td align="left">The stepsize for the leapfrog method [X numeric and &gt; 0]</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb203-1" tabindex="-1"></a><span class="co"># mcmc</span></span>
<span id="cb203-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb203-2" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">SCAMCMC</span>()</span></code></pre></div>
<p>Defaults provide a good starting point, so let’s fit first the model. Note that the argument <code>fit</code> must be set to <code>MCMC</code> while the argument <code>mcmc</code> takes the <code>SCAMCMC</code> object just created.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb204-1" tabindex="-1"></a><span class="co"># fit the model</span></span>
<span id="cb204-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb204-2" tabindex="-1"></a>fitmc00 <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod, <span class="at">fit =</span> <span class="st">&quot;MCMC&quot;</span>, <span class="at">mcmc=</span>mc)</span>
<span id="cb204-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb204-3" tabindex="-1"></a><span class="co"># check acceptance rate</span></span>
<span id="cb204-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb204-4" tabindex="-1"></a><span class="fu">fitSumm</span>(fitmc00)</span></code></pre></div>
<pre><code>##              iters
##                      1
##   nopar        52.0000
##   nlogl             NA
##   maxgrad           NA
##   nobs        176.0000
##   gcv               NA
##   convergence       NA
##   accrate       0.3271</code></pre>
<p>As usual <code>fitSumm</code> store relevant information about the model fit. In the case of an MCMC fit, the information stored includes the number of model parameters (<code>nopar</code>), the number of observations (<code>nobs</code>) and the acceptance rate (<code>accrate</code>).</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb206-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">FLStocks</span>(<span class="at">mle=</span>hke1567 <span class="sc">+</span> fit, <span class="at">mc=</span>hke1567 <span class="sc">+</span> fitmc00))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-88"></span>
<img src="_main_files/figure-html/unnamed-chunk-88-1.png" alt="Stock assessment summaries of maximum likelihood (mle) and monte carlo (mc) fits." width="672" />
<p class="caption">
Figure 10.1: Stock assessment summaries of maximum likelihood (mle) and monte carlo (mc) fits.
</p>
</div>
</div>
<div id="diagnostics-with-coda" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Diagnostics with CODA<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#diagnostics-with-coda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>MCMC diagnostics are used to give the analyst confidence that the posterior distribution of the parameters is unbiased, with symmetric non-correlated distributions of each parameter over which one can make inference.</p>
<p>There exists a large body of literature about MCMC convergence. In this section we will focus on the out-of-the-box methods for metropolis hastings algorithm available to the stock assessment scientist: trace plots, autocorrelation and cross correlation analysis, Geweke diagnostic, Gelman and Rubin’s convergence diagnostic, cumulative means, distribution density and acceptance rate. These tools should be used together to evaluate proper mixing and convergence.</p>
<p><code>ADMB</code> has an hybrid algorithm based on Hamiltonian dynamics which will not be employed here. The reader is invited to consult <span class="citation">Cole C. Monnahan et al. (<a href="#ref-monnahan2019">2019</a>)</span> for more information.</p>
<p>We use the package <code>CODA</code> <span class="citation">(<a href="#ref-coda">Plummer et al. 2006</a>)</span> to run the diagnostics on MCMC fits. One needs to convert the <code>sca</code> output into a <code>mcmc</code> <code>CODA</code> object over which several diagnostics can be ran. The <code>mcmc</code> object is a matrix with the parameters (row = iters, cols= pars).</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb207-1" tabindex="-1"></a><span class="fu">library</span>(coda)</span></code></pre></div>
<p>For demonstration purposes we create a chain with 1000 samples (<code>mcmc=1000</code>) and save every iter (<code>mcsave=1</code>), which will create a highly correlated and unstable chain, and update the initial MCMC fit to also have 1000 samples but obtained by keeping every 100th sample (<code>mcmc=100000</code>, <code>mcsave=100</code>). The latter will have a lower correlation due to the higher thinning.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb208-1" tabindex="-1"></a><span class="co"># update initial fit, control random seed</span></span>
<span id="cb208-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb208-2" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">SCAMCMC</span>(<span class="at">mcmc=</span><span class="dv">100000</span>, <span class="at">mcsave=</span><span class="dv">100</span>, <span class="at">mcseed=</span><span class="dv">10</span>)</span>
<span id="cb208-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb208-3" tabindex="-1"></a>fitmc01 <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod, <span class="at">fit =</span> <span class="st">&quot;MCMC&quot;</span>, <span class="at">mcmc=</span>mc)</span>
<span id="cb208-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb208-4" tabindex="-1"></a>fitmc01.mc <span class="ot">&lt;-</span> FLa4a<span class="sc">::</span><span class="fu">as.mcmc</span>(fitmc01)</span>
<span id="cb208-5"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb208-5" tabindex="-1"></a><span class="co"># highly correlated fit, control random seed</span></span>
<span id="cb208-6"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb208-6" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">SCAMCMC</span>(<span class="at">mcmc=</span><span class="dv">1000</span>, <span class="at">mcsave=</span><span class="dv">1</span>, <span class="at">mcseed=</span><span class="dv">10</span>)</span>
<span id="cb208-7"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb208-7" tabindex="-1"></a>fitmc02 <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod, <span class="at">fit =</span> <span class="st">&quot;MCMC&quot;</span>, <span class="at">mcmc=</span>mc)</span>
<span id="cb208-8"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb208-8" tabindex="-1"></a>fitmc02.mc <span class="ot">&lt;-</span> FLa4a<span class="sc">::</span><span class="fu">as.mcmc</span>(fitmc02)</span></code></pre></div>
<div id="traceplots" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Traceplots<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#traceplots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Trace plots (<code>traceplot()</code>) show the sampled values of a parameter over iterations. A plot that looks like a random, stable “cloud” of points with no trends or drifts, with rapid fluctuations, is a signal of convergence, meaning the chain mixes well and is stationary. If the trace plot shows a strong trend or periodicity, drifts, or long autocorrelated stretches, it means the chain has not converged as expected. Figure <a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#fig:chain01">10.2</a> cleary depicts this difference between the two runs.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb209-1" tabindex="-1"></a><span class="co"># use mcmc.list() to create a list with both runs so they&#39;re plot together</span></span>
<span id="cb209-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb209-2" tabindex="-1"></a><span class="fu">traceplot</span>(<span class="fu">mcmc.list</span>(<span class="at">mc01=</span>fitmc01.mc[,<span class="dv">1</span>], <span class="at">mc02=</span>fitmc02.mc[,<span class="dv">2</span>]), <span class="at">lwd=</span><span class="fl">1.5</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>), <span class="at">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:chain01"></span>
<img src="_main_files/figure-html/chain01-1.png" alt="MCMC chain's trace for the first parameter. High correlation chain in blue, low correlation chain in red." width="672" />
<p class="caption">
Figure 10.2: MCMC chain’s trace for the first parameter. High correlation chain in blue, low correlation chain in red.
</p>
</div>
<p>Plotting the chains for the parameter clearly shows autocorrelation for the first parameter in the blue chain. This initial phase, when the parameter seems to be stuck in a fixed position, is called the “burn-in” phase. These iterations can be dropped by using the <code>burnin()</code> function. Note however that this does not decrease the autocorrelation (Figure <a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#fig:chain01b">10.3</a>).</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb210-1" tabindex="-1"></a><span class="fu">traceplot</span>(FLa4a<span class="sc">::</span><span class="fu">as.mcmc</span>(<span class="fu">burnin</span>(fitmc02, <span class="dv">250</span>))[,<span class="dv">1</span>], <span class="at">lwd=</span><span class="fl">1.5</span>, <span class="at">col=</span><span class="dv">4</span>, <span class="at">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:chain01b"></span>
<img src="_main_files/figure-html/chain01b-1.png" alt="MCMC chain with high autocorrelation after removing the initial 250 samples (burnin period)." width="672" />
<p class="caption">
Figure 10.3: MCMC chain with high autocorrelation after removing the initial 250 samples (burnin period).
</p>
</div>
</div>
<div id="autocorrelation-and-crosscorrelation-analysis" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> Autocorrelation and crosscorrelation analysis<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#autocorrelation-and-crosscorrelation-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Autocorrelation analysis (<code>acf()</code> and <code>acfplot()</code>) is an useful tool to assess stationarity. A stationary chain should have low autocorrelation, meaning that each sample is approximately independent. On the opposite, high autocorrelation indicates slow mixing and possible non-stationarity. Furthermore, in a well mixed chain autocorrelation drops quickly to near zero, while a poor mixing one will display high autocorrelation, which also reduces the efficiency of the search.</p>
<p>The autocorrelation plot will show correlation along the chain for each parameter at different lags. Figure <a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#fig:acf01hc">10.4</a> shows that there is a strong autocorrelation for the first parameter which we would like to avoid, while Figure <a href="#fit:acf01"><strong>??</strong></a> shows much lower correlation.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb211-1" tabindex="-1"></a><span class="fu">acfplot</span>(fitmc02.mc[,<span class="dv">1</span>], <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">main=</span><span class="st">&quot;High correlation chain&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:acf01hc"></span>
<img src="_main_files/figure-html/acf01hc-1.png" alt="Autocorrelation plot of the first parameter in the MCMC chain" width="672" />
<p class="caption">
Figure 10.4: Autocorrelation plot of the first parameter in the MCMC chain
</p>
</div>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb212-1" tabindex="-1"></a><span class="fu">acfplot</span>(fitmc01.mc[,<span class="dv">1</span>], <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">main=</span><span class="st">&quot;Low correlation chain&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:acf01"></span>
<img src="_main_files/figure-html/acf01-1.png" alt="Autocorrelation plot of the first parameter in the MCMC chain" width="672" />
<p class="caption">
Figure 10.5: Autocorrelation plot of the first parameter in the MCMC chain
</p>
</div>
<p>Cross-correlation (<code>crosscorr()</code> and <code>crosscorr.plot()</code>) inspects the pairwise correlation of all parameters, which is a useful tool to assess the efficiency of the sampling process and the independence of the generated samples. If cross-correlations are high, it often means that transitions between states are slow, leading to an increased running time and requiring a larger number of samples to achieve effective independent samples. Conversely, low cross-correlation implies that parameters are explored more independently, leading to faster convergence and better mixing.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb213-1" tabindex="-1"></a><span class="fu">crosscorr.plot</span>(fitmc01.mc, <span class="at">main=</span><span class="st">&quot;Low correlation chain&quot;</span>)</span>
<span id="cb213-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb213-2" tabindex="-1"></a><span class="fu">crosscorr.plot</span>(fitmc02.mc, <span class="at">main=</span><span class="st">&quot;High correlation chain&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:ccr01"></span>
<img src="_main_files/figure-html/ccr01-1.png" alt="Crosscorrelation plots" width="50%" /><img src="_main_files/figure-html/ccr01-2.png" alt="Crosscorrelation plots" width="50%" />
<p class="caption">
Figure 10.6: Crosscorrelation plots
</p>
</div>
</div>
<div id="geweke-diagnostic" class="section level3 hasAnchor" number="10.2.3">
<h3><span class="header-section-number">10.2.3</span> Geweke diagnostic<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#geweke-diagnostic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Geweke diagnostic (<code>geweke.diag()</code> and <code>geweke.plot()</code>) computes the Geweke-Brooks Z-score <span class="citation">(<a href="#ref-Geweke1992">Geweke 1992</a>)</span>, which indicates if the first and following parts of a sample from a Markov chain are drawn from the same distribution as the last part of the chain, usually the last 50% of the samples.</p>
<p>It is an useful way to decide if the first few iterations should be discarded, while also provides information about the stability of the chain. Figure <a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#fig:gew01">10.7</a> shows the Geweke plot for the two MCMC runs.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb214-1" tabindex="-1"></a><span class="fu">geweke.plot</span>(fitmc01.mc[,<span class="dv">1</span>], <span class="at">main=</span><span class="st">&quot;Low correlation chain&quot;</span>)</span>
<span id="cb214-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb214-2" tabindex="-1"></a><span class="fu">geweke.plot</span>(fitmc02.mc[,<span class="dv">1</span>], <span class="at">main=</span><span class="st">&quot;High correlation chain&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:gew01"></span>
<img src="_main_files/figure-html/gew01-1.png" alt="Geweke plot of the first parameter in the MCMC chains" width="50%" /><img src="_main_files/figure-html/gew01-2.png" alt="Geweke plot of the first parameter in the MCMC chains" width="50%" />
<p class="caption">
Figure 10.7: Geweke plot of the first parameter in the MCMC chains
</p>
</div>
<p>The panel on the left shows a much more regular chain, where the different blocks of data show similar distributions. The panel on the right clearly shows the z-score statistic changing out of the confidence intervals until about 400 samples are discarded, which points to the need to drop a set of initial samples.</p>
<p>The Geweke diagnostic is also a good way to look at mixing by comparing the mean and variance of the first part of the chain to the last part. Good mixing will show no significant difference between early and late samples. Poor mixing will show large differences, indicating the chain has not explored the posterior fully.</p>
</div>
<div id="cumulative-means" class="section level3 hasAnchor" number="10.2.4">
<h3><span class="header-section-number">10.2.4</span> Cumulative means<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cumulative-means" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Inspecting the cumulative mean along the chain is another good way to check for the stability of the chain. When the mixing is good the mean stabilizes quickly, and vice-versa if not.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb215-1" tabindex="-1"></a>cm01 <span class="ot">&lt;-</span> fitmc01.mc[,<span class="dv">1</span>]</span>
<span id="cb215-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb215-2" tabindex="-1"></a>cm01 <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(cm01) <span class="sc">/</span> <span class="fu">seq_along</span>(cm01)</span>
<span id="cb215-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb215-3" tabindex="-1"></a>cm02 <span class="ot">&lt;-</span> fitmc02.mc[,<span class="dv">1</span>]</span>
<span id="cb215-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb215-4" tabindex="-1"></a>cm02 <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(cm02) <span class="sc">/</span> <span class="fu">seq_along</span>(cm02)</span>
<span id="cb215-5"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb215-5" tabindex="-1"></a><span class="fu">plot</span>(cm01, <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;samples&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;mean&quot;</span>, <span class="at">main=</span><span class="st">&quot;Low correlation chain&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.52</span>, <span class="sc">-</span><span class="fl">0.42</span>))</span>
<span id="cb215-6"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb215-6" tabindex="-1"></a><span class="fu">plot</span>(cm02, <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;samples&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;mean&quot;</span>, <span class="at">main=</span><span class="st">&quot;High correlation chain&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.52</span>, <span class="sc">-</span><span class="fl">0.42</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cmean01"></span>
<img src="_main_files/figure-html/cmean01-1.png" alt="Cumulative mean plots of the first parameter in the MCMC chains" width="50%" /><img src="_main_files/figure-html/cmean01-2.png" alt="Cumulative mean plots of the first parameter in the MCMC chains" width="50%" />
<p class="caption">
Figure 10.8: Cumulative mean plots of the first parameter in the MCMC chains
</p>
</div>
</div>
<div id="distribution-density" class="section level3 hasAnchor" number="10.2.5">
<h3><span class="header-section-number">10.2.5</span> Distribution density<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#distribution-density" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An important element of MCMC is to produce symmetric posterior distributions, for one it’s a sign that the chain explored the space of the parameter, for other it makes inference about the parameters a lot more robust. If the distributions are skewed or multimodal, estimating the expected value and variance becomes a lot more complicated. As such having symmetric distributions is preferred and should be checked before computing statistics of interest.</p>
<p>Figure <a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#fig:dens01">10.9</a> shows the density plots (<code>densplot()</code>) for both runs, where it shows the symmetric distribution of the uncorrelated chain (left panel) and the bimodal distribution of the correlated chain.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb216-1" tabindex="-1"></a><span class="fu">densplot</span>(fitmc01.mc[,<span class="dv">1</span>], <span class="at">main=</span><span class="st">&quot;Low correlation chain&quot;</span>)</span>
<span id="cb216-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb216-2" tabindex="-1"></a><span class="fu">densplot</span>(fitmc02.mc[,<span class="dv">1</span>], <span class="at">main=</span><span class="st">&quot;High correlation chain&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:dens01"></span>
<img src="_main_files/figure-html/dens01-1.png" alt="Density plots of the first parameter in the MCMC chains" width="50%" /><img src="_main_files/figure-html/dens01-2.png" alt="Density plots of the first parameter in the MCMC chains" width="50%" />
<p class="caption">
Figure 10.9: Density plots of the first parameter in the MCMC chains
</p>
</div>
</div>
<div id="gelman-rubin-statistic" class="section level3 hasAnchor" number="10.2.6">
<h3><span class="header-section-number">10.2.6</span> Gelman-Rubin statistic<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#gelman-rubin-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Gelman-Rubin statistic (<span class="math inline">\(\hat{R}\)</span>) <span class="citation">(<a href="#ref-gelman1992inference">Andrew Gelman and Rubin 1992</a>)</span> can be used to check if multiple chains have reached a stable state and are properly exploring the target distribution. It compares how much variation exists within each chain to the variation between different chains. If all chains are sampling from the same distribution, these variations should be similar, and <span class="math inline">\(\hat{R}\)</span> will be close to 1, otherwise, if it’s greater than 1.1 it suggests that the chains have not yet converged.</p>
<p>To compute <span class="math inline">\(\hat{R}\)</span>, multiple chains are run with different starting points. The algorithm measures how spread out the samples are within each chain and compares it to how much the chains differ from each other. If the chains have not mixed well, they will appear too different from each other, and <span class="math inline">\(\hat{R}\)</span> will be large. If the chains have mixed properly, they will have a similar spread, and the statistic will be close to 1.</p>
<p>To run another chain one makes use of the <code>mcseed</code> argument to make sure the 2 chains start from different places. The Gelman-Rubin statistics is computed by the <code>gelman.diag()</code> method and depicted with <code>gelman.plot()</code>. It’s easy to see the difference between the two fits. While the low corrrelation fit shows values close to 1 for most parameters, the high correlation fit shows a number of large values.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-1" tabindex="-1"></a><span class="co"># low correlation</span></span>
<span id="cb217-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-2" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">SCAMCMC</span>(<span class="at">mcmc=</span><span class="dv">100000</span>, <span class="at">mcsave=</span><span class="dv">100</span>, <span class="at">mcseed=</span><span class="dv">30</span>)</span>
<span id="cb217-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-3" tabindex="-1"></a>fitmc01b <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod, <span class="at">fit =</span> <span class="st">&quot;MCMC&quot;</span>, <span class="at">mcmc=</span>mc)</span>
<span id="cb217-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-4" tabindex="-1"></a>fitmc01b.mc <span class="ot">&lt;-</span> FLa4a<span class="sc">::</span><span class="fu">as.mcmc</span>(fitmc01b)</span>
<span id="cb217-5"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-5" tabindex="-1"></a><span class="co"># highly correlated fit</span></span>
<span id="cb217-6"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-6" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">SCAMCMC</span>(<span class="at">mcmc=</span><span class="dv">1000</span>, <span class="at">mcsave=</span><span class="dv">1</span>, <span class="at">mcseed=</span><span class="dv">30</span>)</span>
<span id="cb217-7"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-7" tabindex="-1"></a>fitmc02b <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod, <span class="at">fit =</span> <span class="st">&quot;MCMC&quot;</span>, <span class="at">mcmc=</span>mc)</span>
<span id="cb217-8"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-8" tabindex="-1"></a>fitmc02b.mc <span class="ot">&lt;-</span> FLa4a<span class="sc">::</span><span class="fu">as.mcmc</span>(fitmc02b)</span>
<span id="cb217-9"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-9" tabindex="-1"></a><span class="co"># create lists for comparison</span></span>
<span id="cb217-10"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-10" tabindex="-1"></a>mclst01 <span class="ot">&lt;-</span> <span class="fu">mcmc.list</span>(<span class="at">a=</span>fitmc01.mc, <span class="at">b=</span>fitmc01b.mc)</span>
<span id="cb217-11"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb217-11" tabindex="-1"></a>mclst02 <span class="ot">&lt;-</span> <span class="fu">mcmc.list</span>(<span class="at">a=</span>fitmc02.mc, <span class="at">b=</span>fitmc02b.mc)</span></code></pre></div>
<pre><code>## Potential scale reduction factors:
## 
##                               Point est. Upper C.I.
## fMod:(Intercept)                   1.001      1.001
## fMod:s(age).1                      1.024      1.112
## fMod:s(age).2                      1.002      1.005
## fMod:s(age).3                      1.021      1.099
## fMod:s(year).1                     1.001      1.011
## fMod:s(year).2                     1.004      1.020
## fMod:s(year).3                     1.011      1.051
## fMod:s(year).4                     1.008      1.040
## fMod:s(year).5                     1.002      1.013
## fMod:s(year).6                     1.004      1.024
## fMod:s(year).7                     1.001      1.007
## fMod:s(year):by1..1                0.999      1.000
## fMod:s(year):by1..2                1.003      1.011
## fMod:s(year):by1..3                1.001      1.005
## fMod:s(year):by1..4                1.003      1.013
## fMod:s(year):by1..5                1.005      1.006
## fMod:s(year):by1..6                1.018      1.088
## fMod:s(year):by1..7                0.999      0.999
## fMod:s(year):by1..8                0.999      1.000
## fMod:s(year):by2..1                1.008      1.039
## fMod:s(year):by2..2                0.999      1.001
## fMod:s(year):by2..3                1.008      1.040
## fMod:s(year):by2..4                1.000      1.004
## fMod:s(year):by2..5                1.003      1.018
## fMod:s(year):by2..6                1.003      1.003
## fMod:s(year):by2..7                1.007      1.037
## fMod:s(year):by2..8                1.000      1.001
## n1Mod:(Intercept)                  1.002      1.013
## n1Mod:s(age).1                     1.000      1.003
## n1Mod:s(age).2                     1.001      1.006
## rMod:(Intercept)                   1.000      1.000
## rMod:factor(year)1                 0.999      0.999
## rMod:factor(year)2                 1.000      1.001
## rMod:factor(year)3                 1.002      1.002
## rMod:factor(year)4                 1.002      1.005
## rMod:factor(year)5                 1.000      1.000
## rMod:factor(year)6                 1.005      1.008
## rMod:factor(year)7                 0.999      0.999
## rMod:factor(year)8                 1.010      1.045
## rMod:factor(year)9                 1.001      1.003
## rMod:factor(year)10                1.000      1.004
## rMod:factor(year)11                1.001      1.008
## rMod:factor(year)12                1.011      1.053
## rMod:factor(year)13                1.003      1.003
## rMod:factor(year)14                1.004      1.019
## rMod:factor(year)15                1.008      1.034
## qMod:IND:(Intercept)               1.003      1.017
## qMod:IND:I(1/(1 + exp(-age)))      1.004      1.017
## vMod:catch:(Intercept)             0.999      0.999
## vMod:catch:s(age).1                1.002      1.013
## vMod:catch:s(age).2                1.001      1.010
## vMod:IND:(Intercept)               1.000      1.000
## 
## Multivariate psrf
## 
## 1.11</code></pre>
<pre><code>## Potential scale reduction factors:
## 
##                               Point est. Upper C.I.
## fMod:(Intercept)                    1.11       1.12
## fMod:s(age).1                       1.09       1.12
## fMod:s(age).2                       1.12       1.20
## fMod:s(age).3                       1.13       1.27
## fMod:s(year).1                      1.11       1.41
## fMod:s(year).2                      2.04       4.32
## fMod:s(year).3                      2.75       6.01
## fMod:s(year).4                      1.72       3.40
## fMod:s(year).5                      1.11       1.41
## fMod:s(year).6                      1.82       3.62
## fMod:s(year).7                      1.08       1.27
## fMod:s(year):by1..1                 2.55       5.44
## fMod:s(year):by1..2                 2.44       6.05
## fMod:s(year):by1..3                 2.41       5.03
## fMod:s(year):by1..4                 1.19       1.38
## fMod:s(year):by1..5                 2.17       4.27
## fMod:s(year):by1..6                 2.27       4.39
## fMod:s(year):by1..7                 2.49       5.58
## fMod:s(year):by1..8                 1.23       1.87
## fMod:s(year):by2..1                 1.08       1.27
## fMod:s(year):by2..2                 1.01       1.01
## fMod:s(year):by2..3                 1.14       1.50
## fMod:s(year):by2..4                 1.87       3.41
## fMod:s(year):by2..5                 1.13       1.33
## fMod:s(year):by2..6                 1.45       2.41
## fMod:s(year):by2..7                 1.08       1.30
## fMod:s(year):by2..8                 1.33       2.03
## n1Mod:(Intercept)                   1.04       1.06
## n1Mod:s(age).1                      1.23       1.46
## n1Mod:s(age).2                      1.19       1.22
## rMod:(Intercept)                    1.15       1.53
## rMod:factor(year)1                  2.19       5.80
## rMod:factor(year)2                  1.12       1.40
## rMod:factor(year)3                  1.26       2.10
## rMod:factor(year)4                  1.19       1.20
## rMod:factor(year)5                  1.78       3.19
## rMod:factor(year)6                  2.32       4.62
## rMod:factor(year)7                  1.07       1.16
## rMod:factor(year)8                  2.15       4.22
## rMod:factor(year)9                  1.07       1.16
## rMod:factor(year)10                 1.21       1.29
## rMod:factor(year)11                 3.29       7.95
## rMod:factor(year)12                 2.67       5.39
## rMod:factor(year)13                 1.32       2.01
## rMod:factor(year)14                 1.03       1.04
## rMod:factor(year)15                 1.98       3.69
## qMod:IND:(Intercept)                1.18       1.62
## qMod:IND:I(1/(1 + exp(-age)))       1.49       2.53
## vMod:catch:(Intercept)              1.75       4.09
## vMod:catch:s(age).1                 1.13       1.36
## vMod:catch:s(age).2                 1.26       1.99
## vMod:IND:(Intercept)                1.54       2.57
## 
## Multivariate psrf
## 
## 16.2</code></pre>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb220-1" tabindex="-1"></a>mclst01 <span class="ot">&lt;-</span> <span class="fu">mcmc.list</span>(<span class="at">a=</span>fitmc01.mc[,<span class="dv">1</span>], <span class="at">b=</span>fitmc01b.mc[,<span class="dv">1</span>])</span>
<span id="cb220-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb220-2" tabindex="-1"></a>mclst02 <span class="ot">&lt;-</span> <span class="fu">mcmc.list</span>(<span class="at">a=</span>fitmc02.mc[,<span class="dv">1</span>], <span class="at">b=</span>fitmc02b.mc[,<span class="dv">1</span>])</span>
<span id="cb220-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb220-3" tabindex="-1"></a><span class="fu">gelman.plot</span>(mclst01, <span class="at">main=</span><span class="st">&quot;Low correlation chain&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>))</span>
<span id="cb220-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb220-4" tabindex="-1"></a><span class="fu">gelman.plot</span>(mclst02, <span class="at">main=</span><span class="st">&quot;High correlation chain&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:gelm01"></span>
<img src="_main_files/figure-html/gelm01-1.png" alt="Gelman-Rubin's diagnostic plots for the first parameter." width="50%" /><img src="_main_files/figure-html/gelm01-2.png" alt="Gelman-Rubin's diagnostic plots for the first parameter." width="50%" />
<p class="caption">
Figure 10.10: Gelman-Rubin’s diagnostic plots for the first parameter.
</p>
</div>
</div>
<div id="acceptance-rate" class="section level3 hasAnchor" number="10.2.7">
<h3><span class="header-section-number">10.2.7</span> Acceptance rate<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#acceptance-rate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The acceptance rate in Markov Chain Monte Carlo (MCMC) methods plays a crucial role in balancing exploration and efficiency when sampling from a posterior distribution. It represents the proportion of proposed states that are accepted in the Markov chain and directly influences mixing, convergence, and the quality of inference.</p>
<p>A low acceptance rate (e.g., &lt;20%) means that most proposed moves are rejected, leading to slow exploration of the posterior distribution. This can result in poor mixing and high autocorrelation between samples <span class="citation">(<a href="#ref-gelman2013bayesian">A. Gelman et al. 2013</a>)</span>. A high acceptance rate (e.g., &gt;80%) suggests that the proposals are too conservative, leading to small moves and highly correlated samples.</p>
<p><span class="citation">Cole C. Monnahan et al. (<a href="#ref-monnahan2019">2019</a>)</span> suggests that the optimal acceptance rate varies by model size, among other things, but is roughly 40%, although models with more parameters should have a lower optimal acceptance rate. <span class="citation">A. Gelman, Gilks, and Roberts (<a href="#ref-gelman97">1997</a>)</span> complementary suggest that for Random Walk Metropolis-Hastings (RWMH) in high-dimensional spaces an optimal acceptance rate is about 25%.</p>
<p>The acceptance rate is reported out of the MCMC fit and can be accessed with <code>fitSumm()</code>. Inspecting the acceptance rate for the models we’re using shows a higher acceptance rate for the high correlation model, although both are above the recommended optimal for high dimensional models, like the models used in stock assessment.</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb221-1" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">hessian_scale=</span><span class="fu">c</span>(<span class="fu">fitSumm</span>(fitmc01)),</span>
<span id="cb221-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb221-2" tabindex="-1"></a>    <span class="at">hessian_noscale=</span><span class="fu">c</span>(<span class="fu">fitSumm</span>(fitmc02)),</span>
<span id="cb221-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb221-3" tabindex="-1"></a>    <span class="at">row.names=</span><span class="fu">rownames</span>(<span class="fu">fitSumm</span>(fitmc01)))</span></code></pre></div>
<pre><code>##             hessian_scale hessian_noscale
## nopar            52.00000          52.000
## nlogl                  NA              NA
## maxgrad                NA              NA
## nobs            176.00000         176.000
## gcv                    NA              NA
## convergence            NA              NA
## accrate           0.31914           0.372</code></pre>
</div>
</div>
<div id="admbs-arguments-to-tune-the-mcmc-algorithm" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> <code>ADMB</code>’s arguments to tune the MCMC algorithm<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#admbs-arguments-to-tune-the-mcmc-algorithm" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section is based on <span class="citation">Cole C. Monnahan et al. (<a href="#ref-monnahan2019">2019</a>)</span> and describes a set of arguments and methods which the stock assessment analyst can use to tune the MCMC algorithm and be more confident on its convergence and follow up inference.</p>
<div id="thinning-rate" class="section level3 hasAnchor" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> Thinning rate<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#thinning-rate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For the Metropolis-Hastings algorithm, the most important tuning option available to the user is the saving rate (the inverse of the thinning rate). This is the rate at which parameters are saved, such that thinning is effectively discarding draws. This tuning option is critical since this algorithm generates auto-correlated parameters by design. The user controls the thinning rate with the argument <code>mcsave</code>.</p>
<p>If N = 1 every single draw is saved (none are thinned out), which generates high autocorrelation, suggesting the need to thin more (save fewer). This is the case of the <code>fitmc02</code> fit. In <code>fitmc01</code> <code>mcsave</code> was increased to 100, by increasing the total samples by 100 and saving every 100th. This helps reduce the autocorrelation and produces independent draws from the posterior of interest.</p>
</div>
<div id="mcscale-and-mcnoscale" class="section level3 hasAnchor" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> mcscale and mcnoscale<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#mcscale-and-mcnoscale" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>ADMB</code> “scales” the covariance matrix up or down, depending on the current acceptance rate, during the first part of the chain. Scaling the covariance matrix down produces proposed sets closer to the current set, and vice versa for scaling up. By default, it scales during the first 500 iterations before thinning, but the user can specify this with <code>mcscale</code> or turn off scaling with <code>mcnoscale</code>. <code>ADMB</code> rescales the covariance matrix every 200 iterations until the acceptance rate is between 0.15 and 0.4, or the scaling period is exceeded. Draws from this tuning phase should be discarded as part of the burn-in.</p>
<p>The code below illustrates the effect in the acceptance rate of not scaling the hessian, the acceptance rate drops significantly, which means poor mixing and higher autocorrelation.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb223-1" tabindex="-1"></a><span class="co"># no scale</span></span>
<span id="cb223-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb223-2" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">SCAMCMC</span>(<span class="at">mcmc=</span><span class="dv">100000</span>, <span class="at">mcsave=</span><span class="dv">100</span>, <span class="at">mcseed=</span><span class="dv">10</span>, <span class="at">mcnoscale=</span><span class="cn">TRUE</span>)</span>
<span id="cb223-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb223-3" tabindex="-1"></a>fitmc01ns <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod, <span class="at">fit =</span> <span class="st">&quot;MCMC&quot;</span>, <span class="at">mcmc=</span>mc)</span>
<span id="cb223-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb223-4" tabindex="-1"></a>fitmc01ns.mc <span class="ot">&lt;-</span> FLa4a<span class="sc">::</span><span class="fu">as.mcmc</span>(fitmc01ns)</span>
<span id="cb223-5"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb223-5" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">hessian_scale=</span><span class="fu">c</span>(<span class="fu">fitSumm</span>(fitmc01)),</span>
<span id="cb223-6"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb223-6" tabindex="-1"></a>    <span class="at">hessian_noscale=</span><span class="fu">c</span>(<span class="fu">fitSumm</span>(fitmc01ns)),</span>
<span id="cb223-7"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb223-7" tabindex="-1"></a>    <span class="at">row.names=</span><span class="fu">rownames</span>(<span class="fu">fitSumm</span>(fitmc01)))</span></code></pre></div>
<pre><code>##             hessian_scale hessian_noscale
## nopar            52.00000        52.00000
## nlogl                  NA              NA
## maxgrad                NA              NA
## nobs            176.00000       176.00000
## gcv                    NA              NA
## convergence            NA              NA
## accrate           0.31914         0.08582</code></pre>
<p>In the next analysis we show the autocorrelation statistics for lags of 0, 1, 5, 10 and 50. When the hessian is not scaled the autocorrelation of lag 1 increased from 0.33 to 0.43.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb225-1" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">hessian_scale=</span><span class="fu">c</span>(<span class="fu">autocorr.diag</span>(fitmc01.mc[,<span class="dv">1</span>])),</span>
<span id="cb225-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb225-2" tabindex="-1"></a>    <span class="at">hessian_noscale=</span><span class="fu">c</span>(<span class="fu">autocorr.diag</span>(fitmc01ns.mc[,<span class="dv">1</span>])),</span>
<span id="cb225-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb225-3" tabindex="-1"></a>    <span class="at">row.names=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">50</span>))</span></code></pre></div>
<pre><code>##    hessian_scale hessian_noscale
## 0    1.000000000    1.0000000000
## 1    0.331021210    0.4283436263
## 5    0.020797197    0.0006163336
## 10   0.038728809    0.0067920000
## 50   0.005681063   -0.0193736621</code></pre>
</div>
<div id="mcprobe" class="section level3 hasAnchor" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> mcprobe<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#mcprobe" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For some models, there may be concern of being “stuck” in a local minimum and simply never proposing a value far enough away to escape it and find other regions of high density. <code>ADMB</code> has a built-in algorithm which modifies the default proposal distribution so it occasionally proposes very distant parameters (i.e. “probes”). The modified proposal distribution is a mixture distribution of Normal and Cauchy distributions.</p>
<p>The <code>mcprobe</code> argument controls how the two distributions are mixed, with larger values being more Cauchy (fatter tails, larger jumps). The range of valid inputs is 0.00001 to 0.499, and if no value is supplied a default of 0.05 is used.</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb227-1" tabindex="-1"></a><span class="co"># more Cauchy</span></span>
<span id="cb227-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb227-2" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">SCAMCMC</span>(<span class="at">mcmc=</span><span class="dv">1000</span>, <span class="at">mcsave=</span><span class="dv">1</span>, <span class="at">mcseed=</span><span class="dv">10</span>, <span class="at">mcprobe=</span><span class="fl">0.45</span>)</span>
<span id="cb227-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb227-3" tabindex="-1"></a>fitmc02p <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod, <span class="at">fit =</span> <span class="st">&quot;MCMC&quot;</span>, <span class="at">mcmc=</span>mc)</span>
<span id="cb227-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb227-4" tabindex="-1"></a>fitmc02p.mc <span class="ot">&lt;-</span> FLa4a<span class="sc">::</span><span class="fu">as.mcmc</span>(fitmc02p)</span>
<span id="cb227-5"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb227-5" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">probe_0.05=</span><span class="fu">c</span>(<span class="fu">fitSumm</span>(fitmc02)),</span>
<span id="cb227-6"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb227-6" tabindex="-1"></a>    <span class="at">probe_0.45=</span><span class="fu">c</span>(<span class="fu">fitSumm</span>(fitmc02p)),</span>
<span id="cb227-7"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb227-7" tabindex="-1"></a>    <span class="at">row.names=</span><span class="fu">rownames</span>(<span class="fu">fitSumm</span>(fitmc02)))</span></code></pre></div>
<pre><code>##             probe_0.05 probe_0.45
## nopar           52.000     52.000
## nlogl               NA         NA
## maxgrad             NA         NA
## nobs           176.000    176.000
## gcv                 NA         NA
## convergence         NA         NA
## accrate          0.372      0.343</code></pre>
<p>In the next analysis we show the autocorrelation statistics for lags of 0, 1, 5, 10 and 50. When the hessian is not scaled the autocorrelation of lag 1 increased from 0.33 to 0.37.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb229-1" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">probe_0.05=</span><span class="fu">c</span>(<span class="fu">autocorr.diag</span>(fitmc02.mc[,<span class="dv">1</span>])), <span class="at">probe_0.45=</span><span class="fu">c</span>(<span class="fu">autocorr.diag</span>(fitmc02p.mc[,<span class="dv">1</span>])))</span></code></pre></div>
<pre><code>##   probe_0.05 probe_0.45
## 1 1.00000000  1.0000000
## 2 0.97474570  0.9771081
## 3 0.86670724  0.8964793
## 4 0.72167253  0.7867470
## 5 0.03102215  0.3936894</code></pre>
</div>
<div id="mcrb" class="section level3 hasAnchor" number="10.3.4">
<h3><span class="header-section-number">10.3.4</span> mcrb<a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#mcrb" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>mcrb</code> option (which stands for “rescaled bounded”) alters the covariance matrix used to propose new parameter sets in the Metropolis-Hastings algorithm. Its intended use is to create a more efficient MCMC sampler so the analyses run faster. This option reduces the estimated correlation between parameters. The value must be integer between 1 and 9, inclusive, with lower values leading to a bigger reduction in correlation.</p>
<p>The option will be most effective under circumstances where the correlation between parameters at the posterior mode is higher than other regions of the parameter space. In this case, the algorithm may make efficient proposals near the posterior mode, but inefficient proposals in other parts of the parameter space. By reducing the correlation using <code>mcrb</code> the proposal function may be more efficient on average across the entire parameter space and require less thinning (and hence run faster).</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb231-1" tabindex="-1"></a><span class="co"># reduce correlation</span></span>
<span id="cb231-2"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb231-2" tabindex="-1"></a>mc <span class="ot">&lt;-</span> <span class="fu">SCAMCMC</span>(<span class="at">mcmc=</span><span class="dv">100000</span>, <span class="at">mcsave=</span><span class="dv">100</span>, <span class="at">mcseed=</span><span class="dv">10</span>, <span class="at">mcrb=</span><span class="dv">9</span>)</span>
<span id="cb231-3"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb231-3" tabindex="-1"></a>fitmc01r <span class="ot">&lt;-</span> <span class="fu">sca</span>(hke1567, hke1567.idx, <span class="at">fmodel=</span>fmod, <span class="at">qmodel=</span>qmod, <span class="at">fit =</span> <span class="st">&quot;MCMC&quot;</span>, <span class="at">mcmc=</span>mc)</span>
<span id="cb231-4"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb231-4" tabindex="-1"></a>fitmc01r.mc <span class="ot">&lt;-</span> FLa4a<span class="sc">::</span><span class="fu">as.mcmc</span>(fitmc01r)</span>
<span id="cb231-5"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb231-5" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">mcrb_no=</span><span class="fu">c</span>(<span class="fu">fitSumm</span>(fitmc01)),</span>
<span id="cb231-6"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb231-6" tabindex="-1"></a>    <span class="at">mcrb_high=</span><span class="fu">c</span>(<span class="fu">fitSumm</span>(fitmc01r)),</span>
<span id="cb231-7"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb231-7" tabindex="-1"></a>    <span class="at">row.names=</span><span class="fu">rownames</span>(<span class="fu">fitSumm</span>(fitmc01)))</span></code></pre></div>
<pre><code>##               mcrb_no mcrb_high
## nopar        52.00000  52.00000
## nlogl              NA        NA
## maxgrad            NA        NA
## nobs        176.00000 176.00000
## gcv                NA        NA
## convergence        NA        NA
## accrate       0.31914   0.26789</code></pre>
<p>In the next analysis we show the cross-correlation plots (Figure <a href="#fig:mcrp"><strong>??</strong></a>).</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb233-1" tabindex="-1"></a><span class="fu">crosscorr.plot</span>(fitmc01.mc, <span class="at">main=</span><span class="st">&quot;No mcrp&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:mcrp-1"></span>
<img src="_main_files/figure-html/mcrp-1.png" alt="Cross correlation for run without mcrp and mcrp of 9." width="50%" />
<p class="caption">
Figure 10.11: Cross correlation for run without mcrp and mcrp of 9.
</p>
</div>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="the-statistical-catch-at-age-stock-assessment-framework-with-markov-chain-monte-carlo-mcmc.html#cb234-1" tabindex="-1"></a><span class="fu">crosscorr.plot</span>(fitmc01r.mc, <span class="at">main=</span><span class="st">&quot;mcrp = 9&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:mcrp-2"></span>
<img src="_main_files/figure-html/mcrp-2.png" alt="Cross correlation for run without mcrp and mcrp of 9." width="50%" />
<p class="caption">
Figure 10.12: Cross correlation for run without mcrp and mcrp of 9.
</p>
</div>

</div>
</div>
</div>
<h3> References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Fournier2012" class="csl-entry">
Fournier, David A., Hans J. Skaug, Johnoel Ancheta, James Ianelli, Arni Magnusson, Mark N. Maunder, Anders Nielsen, and John Sibert. 2012. <span>“A<span>D</span> Model Builder: Using Automatic Differentiation for Statistical Inference of Highly Parameterized Complex Nonlinear Models.”</span> <em>Optim. Methods Softw.</em> 27 (2): 233–49. <a href="https://doi.org/10.1080/10556788.2011.597854">https://doi.org/10.1080/10556788.2011.597854</a>.
</div>
<div id="ref-gelman2013bayesian" class="csl-entry">
Gelman, A., J. B. Carlin, H. S. Stern, D. B. Dunson, A. Vehtari, and D. B. Rubin. 2013. <em>Bayesian Data Analysis, Third Edition</em>. Chapman &amp; Hall/CRC Texts in Statistical Science. Taylor &amp; Francis. <a href="https://books.google.be/books?id=ZXL6AQAAQBAJ">https://books.google.be/books?id=ZXL6AQAAQBAJ</a>.
</div>
<div id="ref-gelman97" class="csl-entry">
Gelman, A., W. R. Gilks, and G. O. Roberts. 1997. <span>“<span class="nocase">Weak convergence and optimal scaling of random walk Metropolis algorithms</span>.”</span> <em>The Annals of Applied Probability</em> 7 (1): 110–20.
</div>
<div id="ref-gelman1992inference" class="csl-entry">
Gelman, Andrew, and Donald B Rubin. 1992. <span>“Inference from Iterative Simulation Using Multiple Sequences.”</span> <em>Statistical Science</em> 7 (4): 457–72.
</div>
<div id="ref-Geweke1992" class="csl-entry">
Geweke, John. 1992. <span>“Evaluating the Accuracy of Sampling-Based Approaches to the Calculation of Posterior Moments.”</span> In <em>Bayesian Statistics, 4 (<span>P</span>eñíscola, 1991)</em>, 169–93. Oxford Univ. Press, New York.
</div>
<div id="ref-gilks1995markov" class="csl-entry">
Gilks, W. R., S. Richardson, and D. Spiegelhalter. 1995. <em>Markov Chain Monte Carlo in Practice</em>. Chapman &amp; Hall/CRC Interdisciplinary Statistics. Taylor &amp; Francis. <a href="https://books.google.be/books?id=TRXrMWY_i2IC">https://books.google.be/books?id=TRXrMWY_i2IC</a>.
</div>
<div id="ref-monnahan2019" class="csl-entry">
Monnahan, Cole C, Trevor A Branch, James T Thorson, Ian J Stewart, and Cody S Szuwalski. 2019. <span>“Overcoming Long <span>Bayesian</span> Run Times in Integrated Fisheries Stock Assessments.”</span> Edited by Shijie Zhou. <em>ICES Journal of Marine Science</em> 76 (6): 1477–88. <a href="https://doi.org/10.1093/icesjms/fsz059">https://doi.org/10.1093/icesjms/fsz059</a>.
</div>
<div id="ref-monnahan2014admbmcmc" class="csl-entry">
Monnahan, Cole C., Melissa L. Muradian, and Peter T. Kuriyama. 2014. <em>A Guide for Bayesian Analysis in AD Model Builder</em>. ADMB Project.
</div>
<div id="ref-neal1993probabilistic" class="csl-entry">
Neal, Radford M. 1993. <span>“Probabilistic Inference Using Markov Chain Monte Carlo Methods.”</span>
</div>
<div id="ref-coda" class="csl-entry">
Plummer, Martyn, Nicky Best, Kate Cowles, and Karen Vines. 2006. <span>“CODA: Convergence Diagnosis and Output Analysis for MCMC.”</span> <em>R News</em> 6 (1): 7–11.
</div>
<div id="ref-robert2005monte" class="csl-entry">
Robert, C., and G. Casella. 2005. <em>Monte Carlo Statistical Methods</em>. Springer Texts in Statistics. Springer New York. <a href="https://books.google.be/books?id=HfhGAxn5GugC">https://books.google.be/books?id=HfhGAxn5GugC</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="uncertainty.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="reference-points.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/10-mcmc.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
